# Site settings
title: "David's "
description: >
  Share about life and learnings.

author: David Ng
email: me@davidng.hk
twitter_username: davidng_hk
github_username: david90

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidng.hk" # the base hostname & protocol for your site

google_analytics_id: UA-143021961-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

